Relax PHP dependency so it works on PHP 8.1.
Roave/you-are-using-it-wrong pull request #130
Opened 2022-05-23 13:34 UTC by drupol

Hey hi there,

I would like to use [marcosh/lamphpda](https://github.com/marcosh/lamphpda/) in a PHP 8.1 project and I'm unable to do it because of this requirement package in it.

```
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - roave/you-are-using-it-wrong[1.0.0, ..., 1.4.0] require php ^7.3.0 -> your php version (8.1.6) does not satisfy that requirement.
    - roave/you-are-using-it-wrong[1.5.0, ..., 1.7.0] require php ^7.4.7 -> your php version (8.1.6) does not satisfy that requirement.
    - roave/you-are-using-it-wrong 1.8.0 requires php ^7.4.7 || ~8.0.0 -> your php version (8.1.6) does not satisfy that requirement.
    - roave/you-are-using-it-wrong[1.9.0, ..., 1.10.0] require php ~8.0.0 -> your php version (8.1.6) does not satisfy that requirement.
    - Root composer.json requires roave/you-are-using-it-wrong ^1 -> satisfiable by roave/you-are-using-it-wrong[1.0.0, ..., 1.10.0].
```

This PR:
* Relax `php` dependency so it can be installed with PHP 8.1
* Add `config.allow-plugins` properties in `composer.json`.

Questions:
* Why keeping a `composer.lock` in the repo?
* Should we update `composer.lock` file? If yes, with wich version of PHP?

Thanks in advance!

2022-05-23 13:43 UTC, Ocramius requested changes

2022-05-23 13:43 UTC, Ocramius commented on composer.json
> +        "php":                       "~8.0.0 || ~8.1.0",
8.1 needs to be checked in CI too

2022-05-23 13:46 UTC, drupol commented on composer.json
> +        "php":                       "~8.0.0 || ~8.1.0",
Pushed the changes, hope it's ok.

2022-05-23 13:54 UTC, Ocramius commented on composer.json
> +        "php":                       "~8.0.0 || ~8.1.0",
See CI output 😁

2022-05-23 13:57 UTC, drupol commented on composer.json
> +        "php":                       "~8.0.0 || ~8.1.0",
Let me do some meditation first :pray:

2022-05-23 14:29 UTC, drupol commented
@Ocramius Could you enable the permission to enable workflow? For some reason it doesn't starts anymore.

2022-05-23 14:30 UTC, Ocramius commented
It only starts automatically after the first merged contribution

2022-11-01 00:32 UTC, Ocramius commented
Handled as part of #132

2022-11-01 00:32 UTC, closed without merging